/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/3d/spring_ball.glb -o components/myModels/SpringBall.jsx -r public 
Author: you.likelihood (https://sketchfab.com/you.likelihood)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/spring-ball-2399d7e0a9e349f78bd817121f5e7815
Title: Spring Ball
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function SpringBall(props) {
  const { nodes, materials } = useGLTF('/3d/spring_ball.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} rotation={[-Math.PI / 2, 0, 0]} >
        <meshLambertMaterial color={props.color}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/3d/spring_ball.glb')
