/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/3d/computer/opt-iphone4.glb -o components/myModels/optPhone4.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useTexture } from '@react-three/drei';
import { Decal } from '@react-three/drei';

export function OptPhone4(props) {
  const { nodes, materials } = useGLTF('/3d/computer/opt-iphone4.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.007, -0.335, -0.005]} scale={0.008}>
        <group scale={100}>
          {/* <mesh geometry={nodes.iPhone__12_Pro_Antenna_0.geometry} material={materials['Antenna.002']} /> */}
          <mesh geometry={nodes.iPhone__12_Pro_BodyFrame_0.geometry} material={materials['BodyFrame.001']} />
          <mesh geometry={nodes.iPhone__12_Pro_GrayGlossy2_0.geometry} material={materials['GrayGlossy2.001']} />
          {/* <mesh geometry={nodes.iPhone__12_Pro_MicrophoneSpeaker_0.geometry} material={materials['MicrophoneSpeaker.001']} /> */}
          <mesh geometry={nodes.iPhone12_Pro_Body_0.geometry} material={materials['Body.002']} />
          {/* <mesh geometry={nodes.Apple_Logo_Logo_0.geometry} material={materials['Logo.002']} /> */}
          <mesh geometry={nodes.Bezel_bezel_0.geometry} material={materials['bezel.002']} />
          <mesh geometry={nodes.FrontCamera_Cameralens_0.geometry} material={materials['Cameralens.001']} />
          <mesh geometry={nodes.FrontCamera_FrontCamera_0.geometry} material={materials['FrontCamera.001']} />
          <mesh geometry={nodes.FrontCamera_Glass_0.geometry} material={materials['Glass.002']} />
          <mesh geometry={nodes.FrontCamera001_bezel001_0.geometry} material={materials['bezel.003']} position={[0, 0, -0.001]} />
          <mesh geometry={nodes.FrontMic_GrayGlossy2_0.geometry} material={materials['GrayGlossy2.001']} />
          <mesh geometry={nodes.FrontMic_MicrophoneSpeaker_0.geometry} material={materials['MicrophoneSpeaker.001']} />
          <mesh geometry={nodes.Camera1_Blackmatte_0.geometry} material={materials['Blackmatte.001']} />
          <mesh geometry={nodes.Camera1_Cameralens_0.geometry} material={materials['Cameralens.001']} />
          <mesh geometry={nodes.Camera1_FrontCamera_0.geometry} material={materials['FrontCamera.001']} />
          <mesh geometry={nodes.Camera1_Glass_0.geometry} material={materials['Glass.002']} />
          <mesh geometry={nodes.Camera1_GrayGlossy_0.geometry} material={materials['GrayGlossy.001']} />
          <mesh geometry={nodes.Camera1_PacificBlue_0.geometry} material={materials['PacificBlue.001']} />
          <mesh geometry={nodes.Camera2_Blackmatte_0.geometry} material={materials['Blackmatte.001']} />
          <mesh geometry={nodes.Camera2_Cameralens_0.geometry} material={materials['Cameralens.001']} />
          <mesh geometry={nodes.Camera2_FrontCamera_0.geometry} material={materials['FrontCamera.001']} />
          <mesh geometry={nodes.Camera2_Glass_0.geometry} material={materials['Glass.002']} />
          <mesh geometry={nodes.Camera2_GrayGlossy_0.geometry} material={materials['GrayGlossy.001']} />
          <mesh geometry={nodes.Camera2_PacificBlue_0.geometry} material={materials['PacificBlue.001']} />
          <mesh geometry={nodes.Camera3_Blackmatte_0.geometry} material={materials['Blackmatte.001']} />
          <mesh geometry={nodes.Camera3_Cameralens_0.geometry} material={materials['Cameralens.001']} />
          <mesh geometry={nodes.Camera3_FrontCamera_0.geometry} material={materials['FrontCamera.001']} />
          <mesh geometry={nodes.Camera3_Glass_0.geometry} material={materials['Glass.002']} />
          <mesh geometry={nodes.Camera3_GrayGlossy_0.geometry} material={materials['GrayGlossy.001']} />
          <mesh geometry={nodes.Camera3_PacificBlue_0.geometry} material={materials['PacificBlue.001']} />
          <mesh geometry={nodes.CameraModule001_Glass_0.geometry} material={materials['Glass.002']} />
          <mesh geometry={nodes.CameraModule002_MicrophoneSpeaker_0.geometry} material={materials['MicrophoneSpeaker.001']} />
          <mesh geometry={nodes.Flash_Flash2_0.geometry} material={materials['Flash2.001']} />
          <mesh geometry={nodes.Flash_Flash_0.geometry} material={materials['Flash.002']} />
          <mesh geometry={nodes.LiDar_LiDar__0.geometry} material={materials['LiDar.001']} />
          <mesh geometry={nodes.Screen_Wallpaper_0001.geometry} material={materials['Wallpaper.002']} />
          {/* <mesh geometry={nodes.Screen_Wallpaper_0001_1.geometry} material={materials['myWallpaper.001']} /> */}

          <mesh geometry={nodes.Screen_Wallpaper_0001_1.geometry}
          >

            <meshBasicMaterial transparent opacity={0} />
            <Decal
            // debug
            position={[0, 0.5, 0]}
            rotation={[0,0,0]}
            scale={1}
            // scale-x={1}
            // scale-y={1}
            >
                <meshBasicMaterial
                map={props.myWallpaper}
                transparent
                polygonOffset
                polygonOffsetFactor={-1}
                />

            </Decal>

          </mesh>

          {/* <mesh geometry={nodes.MuteButton_BodyFrame_0.geometry} material={materials['BodyFrame.001']} /> */}
          {/* <mesh geometry={nodes.Port_Blackmatte_0.geometry} material={materials['Blackmatte.001']} /> */}
          {/* <mesh geometry={nodes.Port_BodyFrame_0.geometry} material={materials['BodyFrame.001']} /> */}
          {/* <mesh geometry={nodes.PowerButton_BodyFrame_0.geometry} material={materials['BodyFrame.001']} /> */}
          {/* <mesh geometry={nodes.SimTray_Blackmatte_0.geometry} material={materials['Blackmatte.001']} /> */}
          {/* <mesh geometry={nodes.SimTray_BodyFrame_0.geometry} material={materials['BodyFrame.001']} /> */}
          {/* <mesh geometry={nodes.VolumeButton_BodyFrame_0.geometry} material={materials['BodyFrame.001']} /> */}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/3d/computer/opt-iphone4.glb')
