"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const { validationResult } = require("express-validator");
const carModel_1 = __importDefault(require("../models/carModel"));
const userModel_1 = __importDefault(require("../models/userModel"));
// (req: Request, res:Response, next: NextFunction)
const today = new Date();
const thisMonth = today.getMonth() + 1;
const todayString = today.getFullYear() + "-" + thisMonth + "-" + today.getDate();
// make months and days less than 10 to be stored with a 0 before
// to be displayed in the date forms on the front end
// as this completedOn, addedOn dates are API generated not front-end form generated
let fixedDate = "";
todayString.split("-").forEach((number, index) => {
    if (index === 1 || index === 2) {
        (Number(number) < 10) ? fixedDate = fixedDate + "-0" + number : fixedDate = fixedDate + "-" + number;
    }
    else if (index === 0) {
        fixedDate = fixedDate + number;
    }
});
const clearImage_1 = require("../util/clearImage");
//API 0.2 - authentication
//API 0.2 - images
const routeValidationErrors = (req, res) => {
    ////////////////////////////////////////////////////////////////
    //get the validation errors array
    //an array of objects with path, msg
    const routeValidationErrors = validationResult(req).errors;
    // console.log(routeValidationErrors);
    //if there is an error, return back to the FE a response
    if (routeValidationErrors.length > 0) {
        //i want to go over each object in the array
        //for each object return its msg as message
        const errors = routeValidationErrors.map((errorObject) => {
            return {
                message: errorObject.msg
            };
        });
        console.log(errors);
        return errors;
    }
    else {
        return false;
    }
    ////////////////////////////////////////////////////////////////
};
exports.addCar = (req, res, next) => __awaiter(void 0, void 0, void 0, function* () {
    ////////////////////////////////////////////////////////////////
    const errors = routeValidationErrors(req, res);
    if (errors)
        return res.status(422).json(errors);
    ////////////////////////////////////////////////////////////////
    //create a car if no errors
    try {
        const { brand, carModel, userId, image } = req.body;
        console.log(req.body);
        console.log(req.file);
        // console.log(name);
        let imageUrl = image;
        if (req.file) {
            imageUrl = "/" + req.file.path;
        }
        // console.log(encryptedPassword);
        const newCar = yield new carModel_1.default({
            brand: brand,
            carModel: carModel,
            userId: userId,
            // API 0.2 - images
            //the path is generated by multer as it was stored on the server
            image: imageUrl,
        });
        yield newCar.save();
        //API 0.2 - user model car object
        //the req is already given the userId in the isAuth middleware when 
        //passing a successful request on the route before accessing this middleware
        const user = yield userModel_1.default.findById(req.userId);
        if (user) {
            user.cars.push(newCar);
            yield user.save();
        }
        // return res.status(201).json(newCar);
        return res.status(200).json(user === null || user === void 0 ? void 0 : user.cars[0]);
    }
    catch (error) {
        return res.status(500).json("Failed to create a new Car");
    }
});
exports.editCar = (req, res, next) => __awaiter(void 0, void 0, void 0, function* () {
    ////////////////////////////////////////////////////////////////
    const errors = routeValidationErrors(req, res);
    if (errors)
        return res.status(422).json(errors);
    ////////////////////////////////////////////////////////////////
    //find and edit car if no errors
    try {
        const { brand, carModel, userId, _id, image } = req.body;
        console.log(req.body._id);
        // console.log(name);
        const currentCar = yield carModel_1.default.findById(_id);
        if (currentCar) {
            // console.log(req.userId);
            // console.log(currentCar.userId);
            //API 0.2 - authentication
            //check the ownership of the currently logged in user accessing this middleware
            //the req.userId is set when accessing isAuth checker
            //which is taken from the token created on login
            if (currentCar.userId.toString() !== req.userId.toString()) {
                return res.status(403).json("Not Authorized");
            }
            currentCar.brand = brand;
            currentCar.carModel = carModel;
            //API 0.2 - images
            // if there is a file in the request given by multer
            const oldImage = currentCar.image;
            if (req.file) {
                currentCar.image = "/" + req.file.path;
            }
            yield currentCar.save();
            if (oldImage !== currentCar.image) {
                (0, clearImage_1.clearImage)(oldImage);
            }
            return res.status(201).json(currentCar);
        }
        else {
            return res.status(404).json("Car not found");
        }
    }
    catch (error) {
        return res.status(500).json("Failed to edit the Car");
    }
});
exports.deleteCar = (req, res, next) => __awaiter(void 0, void 0, void 0, function* () {
    //find and edit car if no errors
    try {
        const { _id } = req.body;
        console.log(req.body);
        // console.log(name);
        const currentCar = yield carModel_1.default.findById(_id);
        if (!currentCar) {
            return res.status(404).json("Car not found to be deleted");
        }
        else {
            if (currentCar.userId.toString() !== req.userId.toString()) {
                return res.status(403).json("Not Authorized");
            }
            //API 0.2 - images
            //remove the image file
            (0, clearImage_1.clearImage)(currentCar.image);
            //remove the car from the DB
            yield carModel_1.default.findByIdAndDelete(_id);
            //API 0.2 - user's car object model
            //remove the car from the user's cars
            const user = yield userModel_1.default.findById(req.userId);
            if (user) {
                // user?.cars.pull(_id);    //pull does not exist on user.cars ?
                user.cars = user.cars.filter((car) => car.toString() !== _id);
                user.save();
            }
            return res.status(201).json("Car deleted successfully");
        }
    }
    catch (error) {
        return res.status(500).json("Failed to delete the Car");
    }
});
//car checks
//this is a new check that will add to the car model a new "check object"
//with the first history-check in it
exports.newCheck = (req, res, next) => __awaiter(void 0, void 0, void 0, function* () {
    ////////////////////////////////////////////////////////////////
    const errors = routeValidationErrors(req, res);
    if (errors)
        return res.status(422).json(errors);
    ////////////////////////////////////////////////////////////////
    console.log(req.body);
    //find and edit car if no errors
    try {
        const { title, color, initialCheck, nextCheck, notes, carId } = req.body;
        // // console.log(req.body._id);
        // // console.log(name);
        const currentCar = yield carModel_1.default.findById(carId);
        if (currentCar) {
            //add the check base
            //add first history item
            currentCar.checks.push({
                name: title,
                color: color,
                history: [{
                        addDate: fixedDate,
                        initialCheck: initialCheck,
                        nextCheck: nextCheck,
                        checkedOn: "",
                        notes: notes,
                    }],
            });
            yield currentCar.save();
            return res.status(201).json(currentCar);
        }
        else {
            return res.status(404).json("Car not found");
        }
    }
    catch (error) {
        return res.status(500).json("Failed to edit the Car");
    }
});
exports.editCheck = (req, res, next) => __awaiter(void 0, void 0, void 0, function* () {
    ////////////////////////////////////////////////////////////////
    const errors = routeValidationErrors(req, res);
    if (errors)
        return res.status(422).json(errors);
    ////////////////////////////////////////////////////////////////
    console.log(req.body);
    //find and edit car if no errors
    try {
        const { title, color, initialCheck, nextCheck, notes, carId, checkIndex, historyIndex, checkedOn } = req.body;
        console.log(req.body);
        // // console.log(name);
        const currentCar = yield carModel_1.default.findById(carId);
        if (currentCar) {
            // let currentCar = originalCar;
            //add the check base
            //modify the currentCar base info and keep the history
            currentCar.checks[+checkIndex] = {
                name: title,
                color: color,
                history: currentCar.checks[+checkIndex].history,
            };
            //modify the currentCar's history
            currentCar.checks[+checkIndex].history[+historyIndex] = {
                addDate: currentCar.checks[+checkIndex].history[+historyIndex].addDate,
                checkedOn: checkedOn,
                initialCheck: initialCheck,
                nextCheck: nextCheck,
                notes: notes,
            };
            yield currentCar.save();
            return res.status(201).json(currentCar);
        }
        else {
            return res.status(404).json("the car to be edited was not found");
        }
    }
    catch (error) {
        return res.status(500).json("Failed to edit the check");
    }
});
exports.deleteCheck = (req, res, next) => __awaiter(void 0, void 0, void 0, function* () {
    ////////////////////////////////////////////////////////////////
    const errors = routeValidationErrors(req, res);
    if (errors)
        return res.status(422).json(errors);
    ////////////////////////////////////////////////////////////////
    console.log(req.body);
    //find and edit car if no errors
    try {
        const { carId, checkIndex } = req.body;
        console.log(req.body);
        // // console.log(name);
        const currentCar = yield carModel_1.default.findById(carId);
        if (currentCar) {
            //filter out the check matching this index
            currentCar.checks = currentCar.checks.filter((check) => check !== currentCar.checks[+checkIndex]);
            yield currentCar.save();
            return res.status(201).json(currentCar);
        }
        else {
            return res.status(404).json("the car to be edited was not found");
        }
    }
    catch (error) {
        return res.status(500).json("Failed to edit the check");
    }
});
exports.completeCheck = (req, res, next) => __awaiter(void 0, void 0, void 0, function* () {
    ////////////////////////////////////////////////////////////////
    const errors = routeValidationErrors(req, res);
    if (errors)
        return res.status(422).json(errors);
    ////////////////////////////////////////////////////////////////
    console.log(req.body);
    //find and edit car if no errors
    try {
        const { carId, checkIndex } = req.body;
        let currentCar = yield carModel_1.default.findById(carId);
        if (currentCar) {
            let tempCar = currentCar;
            // console.log(currentCar.checks[checkIndex].history);
            //add the check base
            //modify the currentCar base info and keep the history
            tempCar.checks[+checkIndex].history[0].checkedOn = fixedDate;
            // console.log(currentCar.checks[checkIndex].history);
            tempCar.checks[+checkIndex].history.unshift({
                addDate: fixedDate,
                checkedOn: "",
                initialCheck: "",
                nextCheck: "",
                notes: "",
            });
            console.log(tempCar.checks[+checkIndex].history);
            currentCar.checks = tempCar.checks;
            //modifying the car sub elements did allow saving the new info
            //to overcome this i used two ideas to help
            //markModified does tell mongoose what has been changed
            //also copying the whole object and not editing the sub elements directly
            currentCar.markModified("checks");
            const saved = yield currentCar.save();
            return res.status(201).json(saved);
        }
        else {
            return res.status(404).json("the car to be edited was not found");
        }
    }
    catch (error) {
        return res.status(500).json("Failed to complete the check");
    }
});
exports.deleteCheckHistoryItem = (req, res, next) => __awaiter(void 0, void 0, void 0, function* () {
    ////////////////////////////////////////////////////////////////
    const errors = routeValidationErrors(req, res);
    if (errors)
        return res.status(422).json(errors);
    ////////////////////////////////////////////////////////////////
    console.log(req.body);
    // arId, checkIndex, historyIndex
    //find and edit car if no errors
    try {
        const { carId, checkIndex, historyIndex } = req.body;
        console.log(req.body);
        // // console.log(name);
        const currentCar = yield carModel_1.default.findById(carId);
        if (currentCar) {
            //filter out the check history item matching this index from the history
            currentCar.checks[+checkIndex].history = currentCar.checks[+checkIndex].history.filter((checkItem) => checkItem !== currentCar.checks[+checkIndex].history[historyIndex]);
            currentCar.markModified("checks");
            yield currentCar.save();
            return res.status(201).json(currentCar);
        }
        else {
            return res.status(404).json("the car to be edited was not found");
        }
    }
    catch (error) {
        return res.status(500).json("Failed to edit the check");
    }
});
