import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

// import StarsCanvas from "@/components/Contact/StarsCanvas";
// import SmoothScroll from "@/components/Scroll/SmoothScroll";
import LinkProvider from "@/components/context";
import Footer from "@/components/footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


// put in the body the header, footer and the children will be the home page.tsx or any other folder page.tsx
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (

     
    <html lang="en" className="">
      <body className={`${inter.className} relative`}>
        
      {/* <StarsCanvas/> */}
        <Nav/>

        {/* all children lifted up beneath the nav length */}
        <main className="mt-[-2.5rem] mb-[4rem]">
        {children}
        </main>

        <Footer/>
      </body>
    </html>
  );
}
